Update firebase-hosting-merge.yml

diff --git a/.github/workflows/firebase-hosting-merge.yml b/.github/workflows/firebase-hosting-merge.yml
--- a/.github/workflows/firebase-hosting-merge.yml
+++ b/.github/workflows/firebase-hosting-merge.yml
@@ -34,8 +34,10 @@ jobs:
 
       - name: Clean cache
         run: |
+          npm cache clean --force
           flutter pub cache repair
           dart pub cache repair
+          flutter pub get
           
       - name: Run build_runner
         run: |
@@ -48,6 +50,35 @@ jobs:
         run: |
           flutter pub get
           dart pub get
+
+      - name: Install Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
+          
+      - name: Install Firebase Tools
+        run: npm install -g firebase-tools@13.11.2
+
+      - name: Clean build
+        run: flutter clean
+      
+      - name: Build Flutter Web
+        run: flutter build web
+
+      - name: Install Firebasse
+        run: npm install firebase
+
+      - name: Deploy to Firebase Hosting
+        run: |
+          npx firebase-tools@latest deploy --only hosting --project redela-81338 --json || echo "Error al implementar en Firebase Hosting: $?"
+          echo "Listando archivos en build/web:"
+          ls -al build/web
+        
+      - name: Deploy to Firebase Hosting
+        run: |
+          firebase deploy --only hosting --project redela-81338 --json || echo "Error al implementar en Firebase Hosting: $?"
+          echo "Listando archivos:"
+          ls -al
         
       - uses: FirebaseExtended/action-hosting-deploy@v0
         with:
