Update firebase-hosting-pull-request.yml

diff --git a/.github/workflows/firebase-hosting-pull-request.yml b/.github/workflows/firebase-hosting-pull-request.yml
--- a/.github/workflows/firebase-hosting-pull-request.yml
+++ b/.github/workflows/firebase-hosting-pull-request.yml
@@ -58,11 +58,20 @@ jobs:
       - name: Install Firebase Tools
         run: npm install -g firebase-tools@13.11.2
 
+      - name: Clean build
+        run: flutter clean
+      
       - name: Build Flutter Web
         run: flutter build web
 
       - name: Install Firebasse
         run: npm install firebase
+
+      - name: Deploy to Firebase Hosting
+        run: |
+          npx firebase-tools@latest deploy --only hosting --project redela-81338 --json || echo "Error al implementar en Firebase Hosting: $?"
+          echo "Listando archivos en build/web:"
+          ls -al build/web
         
       - name: Deploy to Firebase Hosting
         run: |
