Update firebase-hosting-pull-request.yml

diff --git a/.github/workflows/firebase-hosting-pull-request.yml b/.github/workflows/firebase-hosting-pull-request.yml
--- a/.github/workflows/firebase-hosting-pull-request.yml
+++ b/.github/workflows/firebase-hosting-pull-request.yml
@@ -14,17 +14,52 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       
+      - name: Set up Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          flutter-version: '3.22.2'
+          channel: 'stable'
+
+      - run: flutter --version
+
       - name: Set up Dart
         uses: dart-lang/setup-dart@v1
         with:
-          sdk: stable
-        
-      - name: Install dependencies
-        run: dart pub get
+          sdk: '3.4.3'          
+          channel: 'stable'
+          
+      - run: flutter --version
       
+      - name: Grant permissions
+        run: sudo chmod -R 777 .      
+
+      - name: Clean cache
+        run: |
+          flutter pub cache repair
+          dart pub cache repair
+          
       - name: Run build_runner
-        run: dart run build_runner build
+        run: |
+          echo "Directorio de trabajo: $(pwd)"
+          echo "Listando archivos:"
+          ls -al
+          dart run build_runner build || echo "Error al ejecutar build_runner: $?"
+          
+      - name: Install dependencies
+        run: |
+          flutter pub get
+          dart pub get
+
+      - name: Install Firebase Tools
+        run: npm install -g firebase-tools@13.11.2
         
+      - name: Deploy to Firebase Hosting
+        run: |
+          npx firebase-tools@latest deploy --only hosting --project redela-81338 --json || echo "Error al implementar en Firebase Hosting: $?"
+          echo "Listando archivos:"
+          ls -al
+
+          
       - uses: FirebaseExtended/action-hosting-deploy@v0
         with:
           repoToken: ${{ secrets.GITHUB_TOKEN }}
